name: CI

on:
  push:

permissions:
  contents: read

jobs:
  list-test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 26
          cache: npm

      - name: Instalar dependencias
        run: npm ci

      - name: Lint
        run: npm lint

      - name: Test
        run: npm test

      - name: Build
        run: npm run build